Hometask2
alirmon/matprak19okshin pull request #2
Opened 2019-09-30 21:20 UTC by alirmon

2019-10-01 14:06 UTC, illarionovEA requested changes
все задания делаются в ноутбуке, а не py файлах

2019-10-01 16:34 UTC, illarionovEA commented
нужно доделать 6

2019-10-12 10:15 UTC, alirmon commented
@illarionovEA

2019-10-13 12:35 UTC, illarionovEA approved these changes

2019-10-13 13:44 UTC, merged